all:
	make -C samediff
	make -C plebdisc
	make -C srailsdisc

clean:
	make -C samediff clean
	make -C plebdisc clean
	make -C srailsdisc clean

install:
	make -c plebdisc install

.PHONY: install

