. $Header: /n/posole/da/bedk/speech/src/mapping/RCS/lsqsolve.1,v 1.3 1996/02/27 19:43:32 bedk Exp $
.\" A few notes:
.\" i) Don't add extra blank lines - these appear in the output and
.\"    leaves too much space when display on the screen
.\"
.\" This title line needs to be changed to contain your program name,
.\" but the date will be changed automatically by RCS.
.TH LSQSOLVE 1 "$Date: 1996/02/27 19:43:32 $" ICSI
.\" Don't do anything clever in the section below - it messes up the
.\" whatis database that's accessed using "man -k"
.SH NAME
lsqsolve \- helper program for
.I create_mapping
.SH DESCRIPTION
.I lsqsolve
is a helper program for
.I create_mapping
that constructs and solves least-squares problems.  It is not meant to be
run in standalone mode.
.SH AUTHOR
Brian Kingsbury <bedk@icsi.berkeley.edu>
.SH SEE ALSO
.BR create_mapping(1), rasta(1)
